CREATE TABLE `account` (
`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
`username` varchar(32) NOT NULL DEFAULT '',
`salt` binary(32) DEFAULT NULL,
`verifier` binary(32) NOT NULL,
`session_key` binary(40) DEFAULT NULL,
`totp_secret` varbinary(128) DEFAULT NULL,
`email` varchar(255) NOT NULL DEFAULT '',
`reg_mail` varchar(255) NOT NULL DEFAULT '',
`joindate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`last_ip` varchar(15) NOT NULL DEFAULT '127.0.0.1',
`last_attempt_ip` varchar(15) NOT NULL DEFAULT '127.0.0.1',
`failed_logins` int unsigned NOT NULL DEFAULT '0',
`locked` tinyint unsigned NOT NULL DEFAULT '0',
`lock_country` varchar(2) NOT NULL DEFAULT '00',
`last_login` timestamp NULL DEFAULT NULL,
`online` int unsigned NOT NULL DEFAULT '0',
`expansion` tinyint unsigned NOT NULL DEFAULT '2',
`locale` tinyint unsigned NOT NULL DEFAULT '0',
`os` varchar(3) NOT NULL DEFAULT '',
`recruiter` int unsigned NOT NULL DEFAULT '0',
`totaltime` int unsigned NOT NULL DEFAULT '0',
`votePoints` varchar(255) DEFAULT '0',
`restore_key` varchar(255) DEFAULT '1',
PRIMARY KEY (`id`),
UNIQUE KEY `idx_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=877 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Account System'
